version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.14.1
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:118.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7900:7900"
    shm_size: "2g"
    networks:
      - grid

networks:
  grid:
    driver: bridge
