import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/organisms/Footer/Footer";
import Header from "@/components/organisms/Header/Header";
import "@/styles/globals.css";
import { cva } from "@@/styled-system/css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={mainRecipe()}>{children}</main>
        <Footer />
      </body>
    </html>
  );
};

const mainRecipe = cva({
  base: { bg: "GHOUST_WHITE", minHeight: "calc(100vh - 200px)", maxWidth: "100vw" },
});

export default RootLayout;
