name: Deploy migrations

on:
  push:
    branches:
      - main

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON }}

    - name: Deploy migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npx prisma migrate deploy
