name: Deploy storybook

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  deploy-storybook:
    name: Project build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON }}

      - name: Build storybook
        run: npm run build-storybook

      - name: Copy vercel_ignore_build_step.sh
        run: mkdir -p ./storybook-static/shells && cp ./shells/vercel_ignore_build_step.sh ./storybook-static/shells/vercel_ignore_build_step.sh

      - name: Deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
